[site]
title = "Qi Yan (Kian)"
description = "Specially Appointed Associate Research Fellow at the School of Future Technologies, Northeastern University, China."
favicon = "/neu-favicon.png"

[author]
name = "Qi Yan (Kian)"
publication_names = ["Qi Yan"]
title = "Specially Appointed Associate Research Fellow"
institution = "School of Future Technologies, Northeastern University, China"
avatar = "/bio.jpg"

[social]
# Contact information (leave blank or delete to hide)

email = "yanqi@mail.neu.edu.cn"
location = "Shenyang, China"
location_url = "https://maps.google.com/?q=Northeastern+University+Hunnan+Campus"
location_details = [
  "Room B424, Architecture Building,",
  "Hunnan Campus, Northeastern University"
]
google_scholar = "https://scholar.google.com/citations?user=DMi1YmMAAAAJ&hl=en"
orcid = "https://orcid.org/0000-0002-8243-8633"
github = "https://github.com/kian-qiyan"
researchgate = "https://www.researchgate.net/profile/Qi-Yan-44"

[features]
# Display all subpages on a single page
enable_one_page_mode = false

[i18n]
enabled = true
locales = ["zh", "en"]
default_locale = "en"
# "auto" means the locale will be determined by the browser's language setting, "fixed" means the locale will be fixed to the default locale (but can be switched still, if you want to disable, set "enable=false")
mode = "fixed"
fixed_locale = "en"
# If true, PRISM will remember user's language preference in browser's localStorage
persist = true
# Show a language switcher on the top right corner
switcher = true

[i18n.labels]
zh = "中文"
en = "English"

[[navigation]]
title = "About"
type = "page"
target = "about"
href = "/"

[[navigation]]
title = "Publications"
type = "page"
target = "publications"
href = "/publications"
